/* definitions generated by preprocessor, copy into defines.h */
#ifndef	PPINC
#define	PPINC

#define	_ATMEGA16	// device select: _ATMEGAxxxx
#ifdef	__ICCAVR__
#include	"iom16.h"
#endif
#if	__GNUC__
#include	<avr/io.h>
#endif

/* baud rate register value calculation */
#define	CPU_FREQ	16000000

/* definitions for UART control */
#define	BAUD_RATE_LOW_REG	UBRRL
#define	BAUD_RATE_HIGH_REG	UBRRH
#define	UART_CONTROL_REG_A	UCSRA
#define	FRAME_ERROR_BIT		FE
#define	DATA_OVERRUN_BIT	DOR
#define	PARITY_ERROR_BIT	PE
#define	UART_CONTROL_REG_B	UCSRB
#define	ENABLE_TRANSMITTER_BIT	TXEN
#define	ENABLE_RECEIVER_BIT	RXEN
#define	ENABLE_RECEIVE_INTR	RXCIE
#define	ENABLE_SEND_INTR	UDRIE
#define	UART_CONTROL_REG_C	UCSRC
#define	ENABLE_EVEN_PARITY	UPM1
#define	ENABLE_CHARACTER_SIZE_1	UCSZ1
#define	ENABLE_CHARACTER_SIZE_0	UCSZ0
#define	UART_STATUS_REG	UCSRA
#define	TRANSMIT_COMPLETE_BIT	TXC
#define	RECEIVE_COMPLETE_BIT	RXC
#define	UART_DATA_REG	UDR
#define UART_RX_INTR_FUNC	USART_RXC_vect
#define UART_DRE_INTR_FUNC	USART_UDRE_vect

#define UART_BUFFER_SIZE	64

#define BUZZ_DDR        DDRD
#define BUZZPORT        PORTD
#define BUZZ_NO         PD6

#endif
