/* definitions generated by preprocessor, copy into defines.h */
#ifndef	PPINC
#define	PPINC

#include <avr/sfr_defs.h>

#define	_ATMEGA16	// device select: _ATMEGAxxxx
#ifdef	__ICCAVR__
#include	"iom16.h"
#endif
#if	__GNUC__
#include	<avr/io.h>
#endif

/* baud rate register value calculation */
#define	CPU_FREQ	16000000

#define WDTCSR	    WDTCR
#define WDCE        WDTOE

#define WATCHDOG_OFF    (0)
#define WATCHDOG_16MS   (_BV(WDE))
#define WATCHDOG_32MS   (_BV(WDP0) | _BV(WDE))
#define WATCHDOG_64MS   (_BV(WDP1) | _BV(WDE))
#define WATCHDOG_125MS  (_BV(WDP1) | _BV(WDP0) | _BV(WDE))
#define WATCHDOG_250MS  (_BV(WDP2) | _BV(WDE))
#define WATCHDOG_500MS  (_BV(WDP2) | _BV(WDP0) | _BV(WDE))
#define WATCHDOG_1S     (_BV(WDP2) | _BV(WDP1) | _BV(WDE))
#define WATCHDOG_2S     (_BV(WDP2) | _BV(WDP1) | _BV(WDP0) | _BV(WDE))

// Watchdog functions. These are only safe with interrupts turned off.
static inline void watchdogReset(void)
{
  __asm__ __volatile__ (
    "wdr\n"
  );
}

static inline void watchdogConfig(uint8_t x)
{
  WDTCSR = _BV(WDCE) | _BV(WDE);
  WDTCSR = x;
}

/* definitions for UART control */
#define	BAUD_RATE_LOW_REG	UBRRL
#define	BAUD_RATE_HIGH_REG	UBRRH
#define	UART_CONTROL_REG_A	UCSRA
#define ENABLE_DOUBLE_SPEED	U2X
#define	FRAME_ERROR_BIT		FE
#define	DATA_OVERRUN_BIT	DOR
#define	PARITY_ERROR_BIT	PE
#define	UART_CONTROL_REG_B	UCSRB
#define	ENABLE_TRANSMITTER_BIT	TXEN
#define	ENABLE_RECEIVER_BIT	RXEN
#define	ENABLE_RECEIVE_INTR	RXCIE
#define	ENABLE_SEND_INTR	UDRIE
#define	UART_CONTROL_REG_C	UCSRC
#define	REGISTER_SELECT		URSEL
#define	ENABLE_EVEN_PARITY	UPM1
#define	ENABLE_CHARACTER_SIZE_1	UCSZ1
#define	ENABLE_CHARACTER_SIZE_0	UCSZ0
#define	UART_STATUS_REG	UCSRA
#define	TRANSMIT_COMPLETE_BIT	TXC
#define	RECEIVE_COMPLETE_BIT	RXC
#define	UART_DATA_REG	UDR
#define UART_RX_INTR_FUNC	USART_RXC_vect
#define UART_DRE_INTR_FUNC	USART_UDRE_vect

#define ADC_CTRL_STATUS_REG	ADCSRA
#define ENABLE_ADC		ADEN
#define	ADC_START_CONVERSION	ADSC
#define	ENABLE_ADC_AUTO_TRIGGER	ADATE
#define	ADC_INTERRUPT_FLAG	ADIF
#define	ADC_INTERRUPT_ENABLE	ADIE
#define	ADC_PRESCALE_BIT_2	ADPS2
#define	ADC_PRESCALE_BIT_1	ADPS1
#define	ADC_PRESCALE_BIT_0	ADPS0

#define	ADC_DATA_HIGH_REG	ADCH
#define	ADC_DATA_LOW_REG	ADCL

#define SPECIAL_FUNCTION_IO_REG	FIOR
#define	ADC_TRIGGER_SELECT_BIT_2	ADTS2
#define	ADC_TRIGGER_SELECT_BIT_1	ADTS1
#define	ADC_TRIGGER_SELECT_BIT_0	ADTS0

#define ADC_MUX_SELECT_REG	ADMUX
#define ADC_REFERENCE_SELECT_BIT_1	REFS1
#define ADC_REFERENCE_SELECT_BIT_0	REFS0
#define ADC_LEFT_ADJUST_RESULT	ADLAR
#define ADC_MUX_SELECT_BIT4	MUX4
#define ADC_MUX_SELECT_BIT3	MUX3
#define ADC_MUX_SELECT_BIT2	MUX2
#define ADC_MUX_SELECT_BIT1	MUX1
#define ADC_MUX_SELECT_BIT0	MUX0

#define ADC_INTR_FUNC	ADC_vect


#define UART_BUFFER_SIZE	32

#define NFANS			4

#define FAN_ADC_DDR	DDRA
#define FAN_ADC_FIRST_NO	0

#define FAN_DC_DDR	DDRB
#define FAN_DC_PORT	PORTB
#define FAN_DC_FIRST_NO	4

#define FAN_PWM_DDR	DDRB
#define FAN_PWM_PORT	PORTB
#define FAN_PWM_FIRST_NO	0

#define FAN_TACH_DDR	DDRD
#define FAN_TACH_FIRST_NO	2

#define FAN_RPM_DDR	DDRC
#define FAN_RPM_PORT	PORTC
#define FAN_RPM_FIRST_NO	4

#define BUZZ_DDR        DDRD
#define BUZZ_PORT       PORTD
#define BUZZ_NO         PD6

#define OVERTEMP_PORT	PORTC
#define OVERTEMP_NO	PC2

#define MCU_LED_DDR        DDRD
#define MCU_LED_PORT       PORTD
#define MCU_LED_NO         PD7

#define set_output(PIN) PIN ## _DDR |= _BV(PIN ## _NO)
#define set_input(PIN) PIN ## _DDR &= ~_BV(PIN ## _NO)
#define set_pin(PIN, VALUE) PIN ## _PORT = (PIN ## _PORT & ~_BV(PIN ## _NO)) | ((VALUE!=0)<<PIN ## _NO)
#define toggle_pin(PIN) PIN ## _PORT ^= _BV(PIN ## _NO)
#define read_pin(PIN) bit_is_set(PIN ## _PORT, PIN ## _NO)

#endif
